#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x8EB71A70831B56D1 (brian@python.org)
#
Name     : deprecation
Version  : 2.0.5
Release  : 1
URL      : https://files.pythonhosted.org/packages/dd/06/aed49f13984c4acfcd67d699b2a0e96fefd2f9c700ce88a43120eb0363e2/deprecation-2.0.5.tar.gz
Source0  : https://files.pythonhosted.org/packages/dd/06/aed49f13984c4acfcd67d699b2a0e96fefd2f9c700ce88a43120eb0363e2/deprecation-2.0.5.tar.gz
Source99 : https://files.pythonhosted.org/packages/dd/06/aed49f13984c4acfcd67d699b2a0e96fefd2f9c700ce88a43120eb0363e2/deprecation-2.0.5.tar.gz.asc
Summary  : A library to handle automated deprecations
Group    : Development/Tools
License  : Apache-2.0
Requires: deprecation-python3
Requires: deprecation-license
Requires: deprecation-python
Requires: packaging
BuildRequires : buildreq-distutils3
BuildRequires : packaging

%description
===========

%package license
Summary: license components for the deprecation package.
Group: Default

%description license
license components for the deprecation package.


%package python
Summary: python components for the deprecation package.
Group: Default
Requires: deprecation-python3

%description python
python components for the deprecation package.


%package python3
Summary: python3 components for the deprecation package.
Group: Default
Requires: python3-core

%description python3
python3 components for the deprecation package.


%prep
%setup -q -n deprecation-2.0.5

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1533788893
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/deprecation
cp LICENSE %{buildroot}/usr/share/doc/deprecation/LICENSE
python3 -tt setup.py build -b py3 install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(-,root,root,-)
/usr/share/doc/deprecation/LICENSE

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
