#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : deprecation
Version  : 2.0.7
Release  : 8
URL      : https://files.pythonhosted.org/packages/cd/94/8d9d6303f5ddcbf40959fc2b287479bd9a201ea9483373d9b0882ae7c3ad/deprecation-2.0.7.tar.gz
Source0  : https://files.pythonhosted.org/packages/cd/94/8d9d6303f5ddcbf40959fc2b287479bd9a201ea9483373d9b0882ae7c3ad/deprecation-2.0.7.tar.gz
Summary  : A library to handle automated deprecations
Group    : Development/Tools
License  : Apache-2.0
Requires: deprecation-license = %{version}-%{release}
Requires: deprecation-python = %{version}-%{release}
Requires: deprecation-python3 = %{version}-%{release}
Requires: packaging
BuildRequires : buildreq-distutils3
BuildRequires : packaging

%description
deprecation
===========
.. image:: https://readthedocs.org/projects/deprecation/badge/?version=latest
:target: http://deprecation.readthedocs.io/en/latest/
:alt: Documentation Status

%package license
Summary: license components for the deprecation package.
Group: Default

%description license
license components for the deprecation package.


%package python
Summary: python components for the deprecation package.
Group: Default
Requires: deprecation-python3 = %{version}-%{release}

%description python
python components for the deprecation package.


%package python3
Summary: python3 components for the deprecation package.
Group: Default
Requires: python3-core

%description python3
python3 components for the deprecation package.


%prep
%setup -q -n deprecation-2.0.7

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1565731071
# -Werror is for werrorists
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$CFLAGS -fno-lto "
export FFLAGS="$CFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/deprecation
cp LICENSE %{buildroot}/usr/share/package-licenses/deprecation/LICENSE
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/deprecation/LICENSE

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
